# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 11:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('photo', models.FileField(upload_to='documents/')),
                ('heading', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('openings', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=250, null=True)),
                ('linkfb', models.URLField(null=True)),
                ('linkinsta', models.URLField(null=True)),
                ('linklin', models.URLField(null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('authorized', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
