# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='authorized',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
